// vue/WaitlistForm.vue
<template>
  <div v-if="status === 'success'" class="success">
    You're on the list! 🎉
  </div>

  <form v-else @submit.prevent="handleSubmit">
    <input
      v-model="email"
      type="email"
      placeholder="Your email"
      required
    />
    <input
      v-model="name"
      type="text"
      placeholder="Your name (optional)"
    />
    <button type="submit" :disabled="status === 'loading'">
      {{ status === 'loading' ? 'Joining...' : 'Join Waitlist' }}
    </button>
    <div v-if="status === 'error'" class="error">
      Something went wrong. Try again.
    </div>
  </form>
</template>

<script setup>
import { ref } from 'vue';

const WAITLIST_KEY = 'YOUR_WAITLIST_KEY';

const email = ref('');
const name = ref('');
const status = ref('idle'); // idle | loading | success | error

const handleSubmit = async () => {
  status.value = 'loading';

  try {
    const res = await fetch(`https://waitlister.me/s/${WAITLIST_KEY}`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
      body: new URLSearchParams({ 
        email: email.value, 
        name: name.value 
      })
    });

    if (res.ok) {
      status.value = 'success';
      email.value = '';
      name.value = '';
    } else {
      throw new Error();
    }
  } catch {
    status.value = 'error';
  }
};
</script>

// nextjs/WaitlistForm.tsx
'use client';

import { useState, FormEvent } from 'react';

export default function WaitlistForm() {
  const [email, setEmail] = useState('');
  const [name, setName] = useState('');
  const [status, setStatus] = useState<'idle' | 'loading' | 'success' | 'error'>('idle');

  const handleSubmit = async (e: FormEvent) => {
    e.preventDefault();
    setStatus('loading');

    try {
      const res = await fetch('/api/waitlist', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ email, name })
      });

      if (res.ok) {
        setStatus('success');
        setEmail('');
        setName('');
      } else {
        throw new Error();
      }
    } catch {
      setStatus('error');
    }
  };

  if (status === 'success') {
    return <div className="success">You're on the list! 🎉</div>;
  }

  return (
    <form onSubmit={handleSubmit}>
      <input
        type="email"
        value={email}
        onChange={(e) => setEmail(e.target.value)}
        placeholder="Your email"
        required
      />
      <input
        type="text"
        value={name}
        onChange={(e) => setName(e.target.value)}
        placeholder="Your name (optional)"
      />
      <button type="submit" disabled={status === 'loading'}>
        {status === 'loading' ? 'Joining...' : 'Join Waitlist'}
      </button>
      {status === 'error' && (
        <div className="error">Something went wrong. Try again.</div>
      )}
    </form>
  );
}
